### ISSUE TITLE
Allow re-use of Model

### ISSUE THREAD

**Issue by lilith** [atomashpolskiy/rustface#12]
Re-using a model currently requires copying the file bytes and re-parsing; this seems wasteful. Perhaps Model can be made .clone()able?

**Comment by kornelski** [comment]
Same issue here. I hoped there would be an immutable model that I could keep shared and global, and create per-thread detectors from it.

That can't be done with the current architecture. The problem is pretty deep: the model is mutable, because the classifiers are mutable, because their feature maps are mutable, because they try to reuse their temporary buffers instead of reallocating.
