### ISSUE TITLE
Meaning of score

### ISSUE THREAD

**Issue by theduke** [atomashpolskiy/rustface#16]
What is the meaning of the `Faceinfo::score()` data?

As in, what's the range (0-10?), how is it calculated and what does it mean?

**Comment by atomashpolskiy** [comment]
FaceInfo is a rectangular area inside an image, possibly containing a face; its' score represents the level of confidence, if there's really a face and not something else. Higher score is better. This value is calculated by a sophisticated [detection algorithm](https://github.com/atomashpolskiy/rustface/blob/master/src/detector/mod.rs#L236) by using a set of classifiers (pre-trained by the authors of the original library and contained in [mode/seeta_fd_frontal_v1.0.bin](https://github.com/atomashpolskiy/rustface/tree/master/model)). Regarding the range of possible values, they really start from 0, and, [to quote the original documentation](https://github.com/seetaface/SeetaFaceEngine/blob/master/FaceDetection/include/face_detection.h#L93), typical threshold values include 0.95, 2.8 and 4.5, but the user is expected to fine-tune the threshold with a particular set of images (I think, because the algorithm may behave differently on different types of images, so by adjusting the threshold the user may eliminate false positives or increase the number of faces being detected).
